In [1]:
import warnings

In [2]:
import numpy as np
import pandas as pd

In [3]:
train_data = pd.read_csv('BlackFridayTrainNew.csv')

In [4]:
test_data = pd.read_csv('BlackFridayTestNew.csv')

In [5]:
train_data

,Unnamed: 0,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Category_Count,Product_Score,User_Score
0,0,1000001,69042,0,0,10,0,2,0,3,0,0,8370,1,0.120745,0.034113
1,1,1000001,248942,0,0,10,0,2,0,1,6,14,15200,3,0.309043,0.034113
2,2,1000001,87842,0,0,10,0,2,0,12,0,0,1422,1,0.054255,0.034113
3,3,1000001,85442,0,0,10,0,2,0,12,14,0,1057,2,0.181383,0.034113
4,4,1000002,285442,1,6,16,2,4,0,8,0,0,7969,1,0.107979,0.075049
5,5,1000003,193542,1,2,15,0,3,0,1,2,0,15227,2,0.327128,0.028265
6,6,1000004,184942,1,4,7,1,2,1,1,8,17,19215,3,0.765957,0.013645
7,7,1000004,346142,1,4,7,1,2,1,1,15,0,15854,2,0.315426,0.013645
8,8,1000004,97242,1,4,7,1,2,1,1,16,0,15686,2,0.485106,0.013645
9,9,1000005,274942,1,2,20,0,1,1,8,0,0,7871,1,0.421809,0.103314
10,10,1000005,251242,1,2,20,0,1,1,5,11,0,5254,2,0.631383,0.103314
11,11,1000005,14542,1,2,20,0,1,1,8,0,0,3957,1,0.357447,0.103314
12,12,1000005,31342,1,2,20,0,1,1,8,0,0,6073,1,0.019149,0.103314
13,13,1000005,145042,1,2,20,0,1,1,1,2,5,15665,3,0.747872,0.103314
14,14,1000006,231342,0,5,9,0,1,0,5,8,14,5378,3,0.044149,0.045809
15,15,1000006,190242,0,5,9,0,1,0,4,5,0,2079,2,0.101064,0.045809
16,16,1000006,96642,0,5,9,0,1,0,2,3,4,13055,3,0.092553,0.045809
17,17,1000006,58442,0,5,9,0,1,0,5,14,0,8851,2,0.293617,0.045809
18,18,1000007,36842,1,3,1,1,1,1,1,14,16,11788,3,0.470213,0.016569
19,19,1000008,249542,1,2,12,2,4,1,1,5,15,19614,3,0.417553,0.075049
20,20,1000008,220442,1,2,12,2,4,1,5,14,0,8584,2,0.681915,0.075049
21,21,1000008,156442,1,2,12,2,4,1,8,0,0,9872,1,0.444149,0.075049
22,22,1000008,213742,1,2,12,2,4,1,8,0,0,9743,1,0.186702,0.075049
23,23,1000008,214442,1,2,12,2,4,1,8,0,0,5982,1,0.267021,0.075049
24,24,1000008,303442,1,2,12,2,4,1,1,8,14,11927,3,0.189362,0.075049
25,25,1000009,135742,1,2,17,2,0,0,6,8,0,16662,2,0.218085,0.056530
26,26,1000009,39942,1,2,17,2,0,0,8,0,0,5887,1,0.088830,0.056530
27,27,1000009,161442,1,2,17,2,0,0,5,14,0,6973,2,0.267553,0.056530
28,28,1000009,78742,1,2,17,2,0,0,5,8,14,5391,3,0.150000,0.056530
29,29,1000010,85942,0,3,1,1,4,1,2,4,8,16352,3,0.512234,0.217349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,550038,1005995,375436,0,3,1,2,2,1,20,0,0,596,1,0.432979,0.100390
550039,550039,1005996,371644,0,2,0,1,1,1,20,0,0,595,1,0.478191,0.320663
550040,550040,1005997,370853,0,2,7,0,3,0,19,0,0,26,1,0.435106,0.028265
550041,550041,1006000,371644,1,4,17,1,2,1,20,0,0,488,1,0.478191,0.273879
550042,550042,1006002,371644,1,5,0,2,1,1,20,0,0,243,1,0.478191,0.177388
550043,550043,1006003,370293,0,4,17,2,1,0,19,0,0,48,1,0.417553,0.146199
550044,550044,1006004,370853,0,2,15,2,2,0,19,0,0,62,1,0.435106,0.033138
550045,550045,1006005,371644,0,2,5,2,2,1,20,0,0,252,1,0.478191,0.048733
550046,550046,1006006,375436,0,0,0,2,1,0,20,0,0,236,1,0.432979,0.067251
550047,550047,1006009,372445,0,2,12,2,3,0,20,0,0,244,1,0.445213,0.031189
550048,550048,1006010,371644,1,3,0,2,1,0,20,0,0,591,1,0.478191,0.172515
550049,550049,1006011,375436,1,3,15,2,3,0,20,0,0,473,1,0.432979,0.102339
550050,550050,1006012,371644,1,3,15,2,4,1,20,0,0,368,1,0.478191,0.015595
550051,550051,1006013,375436,0,2,20,2,3,0,20,0,0,489,1,0.432979,0.073099
550052,550052,1006016,375436,1,4,1,1,1,1,20,0,0,239,1,0.432979,0.491228
550053,550053,1006017,371644,0,3,7,1,1,0,20,0,0,371,1,0.478191,0.017544
550054,550054,1006018,370293,1,3,1,2,3,0,19,0,0,60,1,0.417553,0.079922
550055,550055,1006019,372445,1,2,0,0,4,0,20,0,0,238,1,0.445213,0.052632
550056,550056,1006022,375436,1,2,17,2,4,0,20,0,0,254,1,0.432979,0.026316
550057,550057,1006023,370853,1,2,0,2,2,1,19,0,0,61,1,0.435106,0.085770
550058,550058,1006024,372445,1,2,12,0,0,1,20,0,0,121,1,0.445213,0.058480
550059,550059,1006025,370853,0,2,1,1,1,0,19,0,0,48,1,0.435106,0.147173
550060,550060,1006026,371644,1,3,6,2,1,1,20,0,0,494,1,0.478191,0.045809
550061,550061,1006029,372445,0,2,1,2,1,1,20,0,0,599,1,0.445213,0.016569
550062,550062,1006032,372445,1,4,7,0,3,0,20,0,0,473,1,0.445213,0.053606
550063,550063,1006033,372445,1,5,13,1,1,1,20,0,0,368,1,0.445213,0.035088
550064,550064,1006035,375436,0,2,1,2,3,0,20,0,0,371,1,0.432979,0.148148
550065,550065,1006036,375436,0,2,15,1,4,1,20,0,0,137,1,0.432979,0.500975
550066,550066,1006038,375436,0,6,1,2,2,0,20,0,0,365,1,0.432979,0.011696
550067,550067,1006039,371644,0,4,0,1,4,1,20,0,0,490,1,0.478191,0.072125

In [6]:
train_data = train_data.drop(['Unnamed: 0'], axis=1)

In [7]:
train_data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Category_Count,Product_Score,User_Score
0,1000001,69042,0,0,10,0,2,0,3,0,0,8370,1,0.120745,0.034113
1,1000001,248942,0,0,10,0,2,0,1,6,14,15200,3,0.309043,0.034113
2,1000001,87842,0,0,10,0,2,0,12,0,0,1422,1,0.054255,0.034113
3,1000001,85442,0,0,10,0,2,0,12,14,0,1057,2,0.181383,0.034113
4,1000002,285442,1,6,16,2,4,0,8,0,0,7969,1,0.107979,0.075049
5,1000003,193542,1,2,15,0,3,0,1,2,0,15227,2,0.327128,0.028265
6,1000004,184942,1,4,7,1,2,1,1,8,17,19215,3,0.765957,0.013645
7,1000004,346142,1,4,7,1,2,1,1,15,0,15854,2,0.315426,0.013645
8,1000004,97242,1,4,7,1,2,1,1,16,0,15686,2,0.485106,0.013645
9,1000005,274942,1,2,20,0,1,1,8,0,0,7871,1,0.421809,0.103314
10,1000005,251242,1,2,20,0,1,1,5,11,0,5254,2,0.631383,0.103314
11,1000005,14542,1,2,20,0,1,1,8,0,0,3957,1,0.357447,0.103314
12,1000005,31342,1,2,20,0,1,1,8,0,0,6073,1,0.019149,0.103314
13,1000005,145042,1,2,20,0,1,1,1,2,5,15665,3,0.747872,0.103314
14,1000006,231342,0,5,9,0,1,0,5,8,14,5378,3,0.044149,0.045809
15,1000006,190242,0,5,9,0,1,0,4,5,0,2079,2,0.101064,0.045809
16,1000006,96642,0,5,9,0,1,0,2,3,4,13055,3,0.092553,0.045809
17,1000006,58442,0,5,9,0,1,0,5,14,0,8851,2,0.293617,0.045809
18,1000007,36842,1,3,1,1,1,1,1,14,16,11788,3,0.470213,0.016569
19,1000008,249542,1,2,12,2,4,1,1,5,15,19614,3,0.417553,0.075049
20,1000008,220442,1,2,12,2,4,1,5,14,0,8584,2,0.681915,0.075049
21,1000008,156442,1,2,12,2,4,1,8,0,0,9872,1,0.444149,0.075049
22,1000008,213742,1,2,12,2,4,1,8,0,0,9743,1,0.186702,0.075049
23,1000008,214442,1,2,12,2,4,1,8,0,0,5982,1,0.267021,0.075049
24,1000008,303442,1,2,12,2,4,1,1,8,14,11927,3,0.189362,0.075049
25,1000009,135742,1,2,17,2,0,0,6,8,0,16662,2,0.218085,0.056530
26,1000009,39942,1,2,17,2,0,0,8,0,0,5887,1,0.088830,0.056530
27,1000009,161442,1,2,17,2,0,0,5,14,0,6973,2,0.267553,0.056530
28,1000009,78742,1,2,17,2,0,0,5,8,14,5391,3,0.150000,0.056530
29,1000010,85942,0,3,1,1,4,1,2,4,8,16352,3,0.512234,0.217349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,375436,0,3,1,2,2,1,20,0,0,596,1,0.432979,0.100390
550039,1005996,371644,0,2,0,1,1,1,20,0,0,595,1,0.478191,0.320663
550040,1005997,370853,0,2,7,0,3,0,19,0,0,26,1,0.435106,0.028265
550041,1006000,371644,1,4,17,1,2,1,20,0,0,488,1,0.478191,0.273879
550042,1006002,371644,1,5,0,2,1,1,20,0,0,243,1,0.478191,0.177388
550043,1006003,370293,0,4,17,2,1,0,19,0,0,48,1,0.417553,0.146199
550044,1006004,370853,0,2,15,2,2,0,19,0,0,62,1,0.435106,0.033138
550045,1006005,371644,0,2,5,2,2,1,20,0,0,252,1,0.478191,0.048733
550046,1006006,375436,0,0,0,2,1,0,20,0,0,236,1,0.432979,0.067251
550047,1006009,372445,0,2,12,2,3,0,20,0,0,244,1,0.445213,0.031189
550048,1006010,371644,1,3,0,2,1,0,20,0,0,591,1,0.478191,0.172515
550049,1006011,375436,1,3,15,2,3,0,20,0,0,473,1,0.432979,0.102339
550050,1006012,371644,1,3,15,2,4,1,20,0,0,368,1,0.478191,0.015595
550051,1006013,375436,0,2,20,2,3,0,20,0,0,489,1,0.432979,0.073099
550052,1006016,375436,1,4,1,1,1,1,20,0,0,239,1,0.432979,0.491228
550053,1006017,371644,0,3,7,1,1,0,20,0,0,371,1,0.478191,0.017544
550054,1006018,370293,1,3,1,2,3,0,19,0,0,60,1,0.417553,0.079922
550055,1006019,372445,1,2,0,0,4,0,20,0,0,238,1,0.445213,0.052632
550056,1006022,375436,1,2,17,2,4,0,20,0,0,254,1,0.432979,0.026316
550057,1006023,370853,1,2,0,2,2,1,19,0,0,61,1,0.435106,0.085770
550058,1006024,372445,1,2,12,0,0,1,20,0,0,121,1,0.445213,0.058480
550059,1006025,370853,0,2,1,1,1,0,19,0,0,48,1,0.435106,0.147173
550060,1006026,371644,1,3,6,2,1,1,20,0,0,494,1,0.478191,0.045809
550061,1006029,372445,0,2,1,2,1,1,20,0,0,599,1,0.445213,0.016569
550062,1006032,372445,1,4,7,0,3,0,20,0,0,473,1,0.445213,0.053606
550063,1006033,372445,1,5,13,1,1,1,20,0,0,368,1,0.445213,0.035088
550064,1006035,375436,0,2,1,2,3,0,20,0,0,371,1,0.432979,0.148148
550065,1006036,375436,0,2,15,1,4,1,20,0,0,137,1,0.432979,0.500975
550066,1006038,375436,0,6,1,2,2,0,20,0,0,365,1,0.432979,0.011696
550067,1006039,371644,0,4,0,1,4,1,20,0,0,490,1,0.478191,0.072125

In [8]:
train_data.dtypes

User_ID                         int64
Product_ID                      int64
Gender                          int64
Age                             int64
Occupation                      int64
City_Category                   int64
Stay_In_Current_City_Years      int64
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2              int64
Product_Category_3              int64
Purchase                        int64
Category_Count                  int64
Product_Score                 float64
User_Score                    float64
dtype: object

In [9]:
test_data

,Unnamed: 0,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,Product_Score,User_Score
0,0,1000004,128942,1,4,7,1,2,1,1,11,0,2,0.478890,0.002262
1,1,1000009,113442,1,2,17,2,0,0,3,5,0,2,0.141134,0.061086
2,2,1000010,288442,0,3,1,1,4,1,5,14,0,2,0.090470,0.228507
3,3,1000010,145342,0,3,1,1,4,1,4,9,0,2,0.009650,0.228507
4,4,1000011,53842,0,2,1,2,1,0,4,5,12,3,0.258142,0.090498
5,5,1000013,350442,1,4,1,2,3,1,2,3,15,3,0.142340,0.058824
6,6,1000013,155442,1,4,1,2,3,1,1,11,15,3,0.214717,0.058824
7,7,1000013,94542,1,4,1,2,3,1,2,4,9,3,0.082027,0.058824
8,8,1000015,161842,1,2,7,0,1,0,10,13,16,3,0.050663,0.104072
9,9,1000022,67942,1,1,15,0,4,0,5,14,0,2,0.183353,0.178733
10,10,1000026,46742,1,2,7,1,2,1,1,2,15,3,0.779252,0.226244
11,11,1000026,40042,1,2,7,1,2,1,5,0,0,1,0.059107,0.226244
12,12,1000026,196542,1,2,7,1,2,1,5,8,14,3,0.212304,0.226244
13,13,1000026,4542,1,2,7,1,2,1,5,8,0,2,0.155609,0.226244
14,14,1000028,159542,0,2,1,2,2,1,10,15,16,3,0.242461,0.072398
15,15,1000029,111542,1,3,7,2,1,0,2,17,0,2,0.255730,0.067873
16,16,1000033,121042,1,4,3,0,1,1,15,0,0,1,0.121834,0.221719
17,17,1000033,344442,1,4,3,0,1,1,5,8,14,3,0.162847,0.221719
18,18,1000034,265242,0,1,0,0,0,0,5,8,0,2,1.000000,0.067873
19,19,1000035,96642,1,4,1,2,4,1,2,3,4,3,0.094089,0.095023
20,20,1000036,303042,1,2,3,1,0,0,5,0,0,1,0.334138,0.190045
21,21,1000036,59642,1,2,3,1,0,0,1,2,3,3,0.184560,0.190045
22,22,1000042,30842,1,2,8,2,0,1,1,2,15,3,0.322075,0.133484
23,23,1000045,346442,0,4,16,0,1,1,1,2,14,3,0.124246,0.167421
24,24,1000045,357242,0,4,16,0,1,1,5,0,0,1,0.055489,0.167421
25,25,1000045,284742,0,4,16,0,1,1,5,12,0,2,0.069964,0.167421
26,26,1000048,110842,1,2,4,1,3,1,1,2,5,3,0.667069,0.350679
27,27,1000048,251642,1,2,4,1,3,1,1,2,4,3,0.120627,0.350679
28,28,1000053,136742,1,2,0,1,1,0,1,14,16,3,0.155609,0.382353
29,29,1000053,97342,1,2,0,1,1,0,1,15,16,3,0.149578,0.382353
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,233569,1005996,184242,0,2,0,1,1,1,9,15,0,2,0.234017,0.309955
233570,233570,1005996,45342,0,2,0,1,1,1,1,5,17,3,0.174910,0.309955
233571,233571,1006001,124642,0,2,7,0,0,1,16,0,0,1,0.173703,0.142534
233572,233572,1006002,121142,1,5,0,2,1,1,8,0,0,1,0.178528,0.158371
233573,233573,1006002,233542,1,5,0,2,1,1,1,15,0,2,0.323281,0.158371
233574,233574,1006002,226342,1,5,0,2,1,1,11,15,0,2,0.316043,0.158371
233575,233575,1006002,284842,1,5,0,2,1,1,1,8,17,3,0.095296,0.158371
233576,233576,1006003,313342,0,4,17,2,1,0,5,0,0,1,0.313631,0.113122
233577,233577,1006010,223542,1,3,0,2,1,0,1,8,17,3,0.208685,0.174208
233578,233578,1006013,20342,0,2,20,2,3,0,1,2,0,2,0.186972,0.063348
233579,233579,1006016,14842,1,4,1,1,1,1,1,2,5,3,0.235223,0.513575
233580,233580,1006016,109542,1,4,1,1,1,1,8,14,17,3,0.243667,0.513575
233581,233581,1006018,71442,1,3,1,2,3,0,15,17,0,2,0.404101,0.101810
233582,233582,1006021,112542,1,2,12,1,2,1,1,11,15,3,0.595899,0.074661
233583,233583,1006021,3442,1,2,12,1,2,1,4,5,8,3,0.469240,0.074661
233584,233584,1006023,262242,1,2,0,2,2,1,1,11,16,3,0.211098,0.070136
233585,233585,1006025,161142,0,2,1,1,1,0,11,0,0,1,0.013269,0.176471
233586,233586,1006026,110742,1,3,6,2,1,1,1,2,8,3,0.820265,0.054299
233587,233587,1006028,162442,1,1,4,0,4,0,1,16,0,2,0.118215,0.020362
233588,233588,1006030,129842,1,2,17,2,1,1,6,8,15,3,0.287093,0.085973
233589,233589,1006030,241442,1,2,17,2,1,1,2,15,0,2,0.065139,0.085973
233590,233590,1006032,252442,1,4,7,0,3,0,8,0,0,1,0.107358,0.065611
233591,233591,1006033,127642,1,5,13,1,1,1,1,2,15,3,0.437877,0.036199
233592,233592,1006035,135742,0,2,1,2,3,0,6,8,0,2,0.184560,0.151584
233593,233593,1006036,255442,0,2,15,1,4,1,8,0,0,1,0.009650,0.463801
233594,233594,1006036,118942,0,2,15,1,4,1,8,0,0,1,0.090470,0.463801
233595,233595,1006036,254642,0,2,15,1,4,1,5,8,0,2,0.083233,0.463801
233596,233596,1006036,31842,0,2,15,1,4,1,1,5,12,3,0.094089,0.463801
233597,233597,1006037,124742,0,4,1,2,4,0,10,16,0,2,0.102533,0.092760
233598,233598,1006039,316642,0,4,0,1,4,1,4,5,0,2,0.200241,0.065611

In [10]:
test_data = test_data.drop(['Unnamed: 0'], axis=1)

In [11]:
test_data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,Product_Score,User_Score
0,1000004,128942,1,4,7,1,2,1,1,11,0,2,0.478890,0.002262
1,1000009,113442,1,2,17,2,0,0,3,5,0,2,0.141134,0.061086
2,1000010,288442,0,3,1,1,4,1,5,14,0,2,0.090470,0.228507
3,1000010,145342,0,3,1,1,4,1,4,9,0,2,0.009650,0.228507
4,1000011,53842,0,2,1,2,1,0,4,5,12,3,0.258142,0.090498
5,1000013,350442,1,4,1,2,3,1,2,3,15,3,0.142340,0.058824
6,1000013,155442,1,4,1,2,3,1,1,11,15,3,0.214717,0.058824
7,1000013,94542,1,4,1,2,3,1,2,4,9,3,0.082027,0.058824
8,1000015,161842,1,2,7,0,1,0,10,13,16,3,0.050663,0.104072
9,1000022,67942,1,1,15,0,4,0,5,14,0,2,0.183353,0.178733
10,1000026,46742,1,2,7,1,2,1,1,2,15,3,0.779252,0.226244
11,1000026,40042,1,2,7,1,2,1,5,0,0,1,0.059107,0.226244
12,1000026,196542,1,2,7,1,2,1,5,8,14,3,0.212304,0.226244
13,1000026,4542,1,2,7,1,2,1,5,8,0,2,0.155609,0.226244
14,1000028,159542,0,2,1,2,2,1,10,15,16,3,0.242461,0.072398
15,1000029,111542,1,3,7,2,1,0,2,17,0,2,0.255730,0.067873
16,1000033,121042,1,4,3,0,1,1,15,0,0,1,0.121834,0.221719
17,1000033,344442,1,4,3,0,1,1,5,8,14,3,0.162847,0.221719
18,1000034,265242,0,1,0,0,0,0,5,8,0,2,1.000000,0.067873
19,1000035,96642,1,4,1,2,4,1,2,3,4,3,0.094089,0.095023
20,1000036,303042,1,2,3,1,0,0,5,0,0,1,0.334138,0.190045
21,1000036,59642,1,2,3,1,0,0,1,2,3,3,0.184560,0.190045
22,1000042,30842,1,2,8,2,0,1,1,2,15,3,0.322075,0.133484
23,1000045,346442,0,4,16,0,1,1,1,2,14,3,0.124246,0.167421
24,1000045,357242,0,4,16,0,1,1,5,0,0,1,0.055489,0.167421
25,1000045,284742,0,4,16,0,1,1,5,12,0,2,0.069964,0.167421
26,1000048,110842,1,2,4,1,3,1,1,2,5,3,0.667069,0.350679
27,1000048,251642,1,2,4,1,3,1,1,2,4,3,0.120627,0.350679
28,1000053,136742,1,2,0,1,1,0,1,14,16,3,0.155609,0.382353
29,1000053,97342,1,2,0,1,1,0,1,15,16,3,0.149578,0.382353
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,1005996,184242,0,2,0,1,1,1,9,15,0,2,0.234017,0.309955
233570,1005996,45342,0,2,0,1,1,1,1,5,17,3,0.174910,0.309955
233571,1006001,124642,0,2,7,0,0,1,16,0,0,1,0.173703,0.142534
233572,1006002,121142,1,5,0,2,1,1,8,0,0,1,0.178528,0.158371
233573,1006002,233542,1,5,0,2,1,1,1,15,0,2,0.323281,0.158371
233574,1006002,226342,1,5,0,2,1,1,11,15,0,2,0.316043,0.158371
233575,1006002,284842,1,5,0,2,1,1,1,8,17,3,0.095296,0.158371
233576,1006003,313342,0,4,17,2,1,0,5,0,0,1,0.313631,0.113122
233577,1006010,223542,1,3,0,2,1,0,1,8,17,3,0.208685,0.174208
233578,1006013,20342,0,2,20,2,3,0,1,2,0,2,0.186972,0.063348
233579,1006016,14842,1,4,1,1,1,1,1,2,5,3,0.235223,0.513575
233580,1006016,109542,1,4,1,1,1,1,8,14,17,3,0.243667,0.513575
233581,1006018,71442,1,3,1,2,3,0,15,17,0,2,0.404101,0.101810
233582,1006021,112542,1,2,12,1,2,1,1,11,15,3,0.595899,0.074661
233583,1006021,3442,1,2,12,1,2,1,4,5,8,3,0.469240,0.074661
233584,1006023,262242,1,2,0,2,2,1,1,11,16,3,0.211098,0.070136
233585,1006025,161142,0,2,1,1,1,0,11,0,0,1,0.013269,0.176471
233586,1006026,110742,1,3,6,2,1,1,1,2,8,3,0.820265,0.054299
233587,1006028,162442,1,1,4,0,4,0,1,16,0,2,0.118215,0.020362
233588,1006030,129842,1,2,17,2,1,1,6,8,15,3,0.287093,0.085973
233589,1006030,241442,1,2,17,2,1,1,2,15,0,2,0.065139,0.085973
233590,1006032,252442,1,4,7,0,3,0,8,0,0,1,0.107358,0.065611
233591,1006033,127642,1,5,13,1,1,1,1,2,15,3,0.437877,0.036199
233592,1006035,135742,0,2,1,2,3,0,6,8,0,2,0.184560,0.151584
233593,1006036,255442,0,2,15,1,4,1,8,0,0,1,0.009650,0.463801
233594,1006036,118942,0,2,15,1,4,1,8,0,0,1,0.090470,0.463801
233595,1006036,254642,0,2,15,1,4,1,5,8,0,2,0.083233,0.463801
233596,1006036,31842,0,2,15,1,4,1,1,5,12,3,0.094089,0.463801
233597,1006037,124742,0,4,1,2,4,0,10,16,0,2,0.102533,0.092760
233598,1006039,316642,0,4,0,1,4,1,4,5,0,2,0.200241,0.065611

In [12]:
x_train = train_data.iloc[:, 0:14]

In [13]:
x_train

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Category_Count,Product_Score
0,1000001,69042,0,0,10,0,2,0,3,0,0,8370,1,0.120745
1,1000001,248942,0,0,10,0,2,0,1,6,14,15200,3,0.309043
2,1000001,87842,0,0,10,0,2,0,12,0,0,1422,1,0.054255
3,1000001,85442,0,0,10,0,2,0,12,14,0,1057,2,0.181383
4,1000002,285442,1,6,16,2,4,0,8,0,0,7969,1,0.107979
5,1000003,193542,1,2,15,0,3,0,1,2,0,15227,2,0.327128
6,1000004,184942,1,4,7,1,2,1,1,8,17,19215,3,0.765957
7,1000004,346142,1,4,7,1,2,1,1,15,0,15854,2,0.315426
8,1000004,97242,1,4,7,1,2,1,1,16,0,15686,2,0.485106
9,1000005,274942,1,2,20,0,1,1,8,0,0,7871,1,0.421809
10,1000005,251242,1,2,20,0,1,1,5,11,0,5254,2,0.631383
11,1000005,14542,1,2,20,0,1,1,8,0,0,3957,1,0.357447
12,1000005,31342,1,2,20,0,1,1,8,0,0,6073,1,0.019149
13,1000005,145042,1,2,20,0,1,1,1,2,5,15665,3,0.747872
14,1000006,231342,0,5,9,0,1,0,5,8,14,5378,3,0.044149
15,1000006,190242,0,5,9,0,1,0,4,5,0,2079,2,0.101064
16,1000006,96642,0,5,9,0,1,0,2,3,4,13055,3,0.092553
17,1000006,58442,0,5,9,0,1,0,5,14,0,8851,2,0.293617
18,1000007,36842,1,3,1,1,1,1,1,14,16,11788,3,0.470213
19,1000008,249542,1,2,12,2,4,1,1,5,15,19614,3,0.417553
20,1000008,220442,1,2,12,2,4,1,5,14,0,8584,2,0.681915
21,1000008,156442,1,2,12,2,4,1,8,0,0,9872,1,0.444149
22,1000008,213742,1,2,12,2,4,1,8,0,0,9743,1,0.186702
23,1000008,214442,1,2,12,2,4,1,8,0,0,5982,1,0.267021
24,1000008,303442,1,2,12,2,4,1,1,8,14,11927,3,0.189362
25,1000009,135742,1,2,17,2,0,0,6,8,0,16662,2,0.218085
26,1000009,39942,1,2,17,2,0,0,8,0,0,5887,1,0.088830
27,1000009,161442,1,2,17,2,0,0,5,14,0,6973,2,0.267553
28,1000009,78742,1,2,17,2,0,0,5,8,14,5391,3,0.150000
29,1000010,85942,0,3,1,1,4,1,2,4,8,16352,3,0.512234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,375436,0,3,1,2,2,1,20,0,0,596,1,0.432979
550039,1005996,371644,0,2,0,1,1,1,20,0,0,595,1,0.478191
550040,1005997,370853,0,2,7,0,3,0,19,0,0,26,1,0.435106
550041,1006000,371644,1,4,17,1,2,1,20,0,0,488,1,0.478191
550042,1006002,371644,1,5,0,2,1,1,20,0,0,243,1,0.478191
550043,1006003,370293,0,4,17,2,1,0,19,0,0,48,1,0.417553
550044,1006004,370853,0,2,15,2,2,0,19,0,0,62,1,0.435106
550045,1006005,371644,0,2,5,2,2,1,20,0,0,252,1,0.478191
550046,1006006,375436,0,0,0,2,1,0,20,0,0,236,1,0.432979
550047,1006009,372445,0,2,12,2,3,0,20,0,0,244,1,0.445213
550048,1006010,371644,1,3,0,2,1,0,20,0,0,591,1,0.478191
550049,1006011,375436,1,3,15,2,3,0,20,0,0,473,1,0.432979
550050,1006012,371644,1,3,15,2,4,1,20,0,0,368,1,0.478191
550051,1006013,375436,0,2,20,2,3,0,20,0,0,489,1,0.432979
550052,1006016,375436,1,4,1,1,1,1,20,0,0,239,1,0.432979
550053,1006017,371644,0,3,7,1,1,0,20,0,0,371,1,0.478191
550054,1006018,370293,1,3,1,2,3,0,19,0,0,60,1,0.417553
550055,1006019,372445,1,2,0,0,4,0,20,0,0,238,1,0.445213
550056,1006022,375436,1,2,17,2,4,0,20,0,0,254,1,0.432979
550057,1006023,370853,1,2,0,2,2,1,19,0,0,61,1,0.435106
550058,1006024,372445,1,2,12,0,0,1,20,0,0,121,1,0.445213
550059,1006025,370853,0,2,1,1,1,0,19,0,0,48,1,0.435106
550060,1006026,371644,1,3,6,2,1,1,20,0,0,494,1,0.478191
550061,1006029,372445,0,2,1,2,1,1,20,0,0,599,1,0.445213
550062,1006032,372445,1,4,7,0,3,0,20,0,0,473,1,0.445213
550063,1006033,372445,1,5,13,1,1,1,20,0,0,368,1,0.445213
550064,1006035,375436,0,2,1,2,3,0,20,0,0,371,1,0.432979
550065,1006036,375436,0,2,15,1,4,1,20,0,0,137,1,0.432979
550066,1006038,375436,0,6,1,2,2,0,20,0,0,365,1,0.432979
550067,1006039,371644,0,4,0,1,4,1,20,0,0,490,1,0.478191

In [14]:
y_train = train_data.iloc[:, 14]

In [15]:
y_train

0         0.034113
1         0.034113
2         0.034113
3         0.034113
4         0.075049
5         0.028265
6         0.013645
7         0.013645
8         0.013645
9         0.103314
10        0.103314
11        0.103314
12        0.103314
13        0.103314
14        0.045809
15        0.045809
16        0.045809
17        0.045809
18        0.016569
19        0.075049
20        0.075049
21        0.075049
22        0.075049
23        0.075049
24        0.075049
25        0.056530
26        0.056530
27        0.056530
28        0.056530
29        0.217349
            ...
550038    0.100390
550039    0.320663
550040    0.028265
550041    0.273879
550042    0.177388
550043    0.146199
550044    0.033138
550045    0.048733
550046    0.067251
550047    0.031189
550048    0.172515
550049    0.102339
550050    0.015595
550051    0.073099
550052    0.491228
550053    0.017544
550054    0.079922
550055    0.052632
550056    0.026316
550057    0.085770
550058    0.058480
550059    0.147173
550060    0.045809
550061    0.016569
550062    0.053606
550063    0.035088
550064    0.148148
550065    0.500975
550066    0.011696
550067    0.072125
Name: User_Score, Length: 550068, dtype: float64

In [16]:
from sklearn.ensemble import RandomForestRegressor

In [17]:
# test_data = test_data.drop(['Purchase'], axis=1)

In [18]:
regr = RandomForestRegressor(n_estimators=100, max_depth=7, n_jobs=-1)
regr.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=7,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [19]:
result = regr.predict(test_data)
result

array([0.2395012 , 0.08406741, 0.22235675, ..., 0.31011752, 0.11949431,
       0.07212476])

In [20]:
test_data['Purchase'] = result

In [21]:
finalSolution = test_data[['User_ID', 'Product_ID', 'Purchase']]

In [22]:
finalSolution

        User_ID  Product_ID  Purchase
0       1000004      128942  0.239501
1       1000009      113442  0.084067
2       1000010      288442  0.222357
3       1000010      145342  0.222357
4       1000011       53842  0.078462
5       1000013      350442  0.089442
6       1000013      155442  0.089442
7       1000013       94542  0.089442
8       1000015      161842  0.234202
9       1000022       67942  0.160192
10      1000026       46742  0.238231
11      1000026       40042  0.238231
12      1000026      196542  0.238231
13      1000026        4542  0.238231
14      1000028      159542  0.078099
15      1000029      111542  0.073522
16      1000033      121042  0.166023
17      1000033      344442  0.166023
18      1000034      265242  0.221415
19      1000035       96642  0.089442
20      1000036      303042  0.239094
21      1000036       59642  0.239094
22      1000042       30842  0.073522
23      1000045      346442  0.209117
24      1000045      357242  0.209117
25      1000045      284742  0.209117
26      1000048      110842  0.237688
27      1000048      251642  0.237688
28      1000053      136742  0.228005
29      1000053       97342  0.228005
...         ...         ...       ...
233569  1005996      184242  0.303782
233570  1005996       45342  0.303782
233571  1006001      124642  0.367599
233572  1006002      121142  0.154134
233573  1006002      233542  0.154134
233574  1006002      226342  0.154134
233575  1006002      284842  0.154134
233576  1006003      313342  0.125480
233577  1006010      223542  0.152035
233578  1006013       20342  0.126931
233579  1006016       14842  0.301982
233580  1006016      109542  0.301982
233581  1006018       71442  0.098269
233582  1006021      112542  0.215758
233583  1006021        3442  0.215758
233584  1006023      262242  0.141345
233585  1006025      161142  0.208915
233586  1006026      110742  0.095437
233587  1006028      162442  0.370449
233588  1006030      129842  0.095437
233589  1006030      241442  0.091219
233590  1006032      252442  0.370449
233591  1006033      127642  0.215758
233592  1006035      135742  0.132974
233593  1006036      255442  0.310118
233594  1006036      118942  0.310118
233595  1006036      254642  0.310118
233596  1006036       31842  0.310118
233597  1006037      124742  0.119494
233598  1006039      316642  0.072125

[233599 rows x 3 columns]

In [23]:
finalSolution.to_csv('RandomForest.csv')

In [24]:
finalSolution['Purchase'] = result

/Users/suhaniladani/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [25]:
finalSolution

        User_ID  Product_ID  Purchase
0       1000004      128942  0.239501
1       1000009      113442  0.084067
2       1000010      288442  0.222357
3       1000010      145342  0.222357
4       1000011       53842  0.078462
5       1000013      350442  0.089442
6       1000013      155442  0.089442
7       1000013       94542  0.089442
8       1000015      161842  0.234202
9       1000022       67942  0.160192
10      1000026       46742  0.238231
11      1000026       40042  0.238231
12      1000026      196542  0.238231
13      1000026        4542  0.238231
14      1000028      159542  0.078099
15      1000029      111542  0.073522
16      1000033      121042  0.166023
17      1000033      344442  0.166023
18      1000034      265242  0.221415
19      1000035       96642  0.089442
20      1000036      303042  0.239094
21      1000036       59642  0.239094
22      1000042       30842  0.073522
23      1000045      346442  0.209117
24      1000045      357242  0.209117
25      1000045      284742  0.209117
26      1000048      110842  0.237688
27      1000048      251642  0.237688
28      1000053      136742  0.228005
29      1000053       97342  0.228005
...         ...         ...       ...
233569  1005996      184242  0.303782
233570  1005996       45342  0.303782
233571  1006001      124642  0.367599
233572  1006002      121142  0.154134
233573  1006002      233542  0.154134
233574  1006002      226342  0.154134
233575  1006002      284842  0.154134
233576  1006003      313342  0.125480
233577  1006010      223542  0.152035
233578  1006013       20342  0.126931
233579  1006016       14842  0.301982
233580  1006016      109542  0.301982
233581  1006018       71442  0.098269
233582  1006021      112542  0.215758
233583  1006021        3442  0.215758
233584  1006023      262242  0.141345
233585  1006025      161142  0.208915
233586  1006026      110742  0.095437
233587  1006028      162442  0.370449
233588  1006030      129842  0.095437
233589  1006030      241442  0.091219
233590  1006032      252442  0.370449
233591  1006033      127642  0.215758
233592  1006035      135742  0.132974
233593  1006036      255442  0.310118
233594  1006036      118942  0.310118
233595  1006036      254642  0.310118
233596  1006036       31842  0.310118
233597  1006037      124742  0.119494
233598  1006039      316642  0.072125

[233599 rows x 3 columns]

In [26]:
finalSolution.to_csv('Result.csv')

In [27]:
from sklearn import linear_model

In [28]:
lm = linear_model.LinearRegression()

In [29]:
model = lm.fit(x_train, y_train)

In [30]:
test_data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,Product_Score,User_Score,Purchase
0,1000004,128942,1,4,7,1,2,1,1,11,0,2,0.478890,0.002262,0.239501
1,1000009,113442,1,2,17,2,0,0,3,5,0,2,0.141134,0.061086,0.084067
2,1000010,288442,0,3,1,1,4,1,5,14,0,2,0.090470,0.228507,0.222357
3,1000010,145342,0,3,1,1,4,1,4,9,0,2,0.009650,0.228507,0.222357
4,1000011,53842,0,2,1,2,1,0,4,5,12,3,0.258142,0.090498,0.078462
5,1000013,350442,1,4,1,2,3,1,2,3,15,3,0.142340,0.058824,0.089442
6,1000013,155442,1,4,1,2,3,1,1,11,15,3,0.214717,0.058824,0.089442
7,1000013,94542,1,4,1,2,3,1,2,4,9,3,0.082027,0.058824,0.089442
8,1000015,161842,1,2,7,0,1,0,10,13,16,3,0.050663,0.104072,0.234202
9,1000022,67942,1,1,15,0,4,0,5,14,0,2,0.183353,0.178733,0.160192
10,1000026,46742,1,2,7,1,2,1,1,2,15,3,0.779252,0.226244,0.238231
11,1000026,40042,1,2,7,1,2,1,5,0,0,1,0.059107,0.226244,0.238231
12,1000026,196542,1,2,7,1,2,1,5,8,14,3,0.212304,0.226244,0.238231
13,1000026,4542,1,2,7,1,2,1,5,8,0,2,0.155609,0.226244,0.238231
14,1000028,159542,0,2,1,2,2,1,10,15,16,3,0.242461,0.072398,0.078099
15,1000029,111542,1,3,7,2,1,0,2,17,0,2,0.255730,0.067873,0.073522
16,1000033,121042,1,4,3,0,1,1,15,0,0,1,0.121834,0.221719,0.166023
17,1000033,344442,1,4,3,0,1,1,5,8,14,3,0.162847,0.221719,0.166023
18,1000034,265242,0,1,0,0,0,0,5,8,0,2,1.000000,0.067873,0.221415
19,1000035,96642,1,4,1,2,4,1,2,3,4,3,0.094089,0.095023,0.089442
20,1000036,303042,1,2,3,1,0,0,5,0,0,1,0.334138,0.190045,0.239094
21,1000036,59642,1,2,3,1,0,0,1,2,3,3,0.184560,0.190045,0.239094
22,1000042,30842,1,2,8,2,0,1,1,2,15,3,0.322075,0.133484,0.073522
23,1000045,346442,0,4,16,0,1,1,1,2,14,3,0.124246,0.167421,0.209117
24,1000045,357242,0,4,16,0,1,1,5,0,0,1,0.055489,0.167421,0.209117
25,1000045,284742,0,4,16,0,1,1,5,12,0,2,0.069964,0.167421,0.209117
26,1000048,110842,1,2,4,1,3,1,1,2,5,3,0.667069,0.350679,0.237688
27,1000048,251642,1,2,4,1,3,1,1,2,4,3,0.120627,0.350679,0.237688
28,1000053,136742,1,2,0,1,1,0,1,14,16,3,0.155609,0.382353,0.228005
29,1000053,97342,1,2,0,1,1,0,1,15,16,3,0.149578,0.382353,0.228005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,1005996,184242,0,2,0,1,1,1,9,15,0,2,0.234017,0.309955,0.303782
233570,1005996,45342,0,2,0,1,1,1,1,5,17,3,0.174910,0.309955,0.303782
233571,1006001,124642,0,2,7,0,0,1,16,0,0,1,0.173703,0.142534,0.367599
233572,1006002,121142,1,5,0,2,1,1,8,0,0,1,0.178528,0.158371,0.154134
233573,1006002,233542,1,5,0,2,1,1,1,15,0,2,0.323281,0.158371,0.154134
233574,1006002,226342,1,5,0,2,1,1,11,15,0,2,0.316043,0.158371,0.154134
233575,1006002,284842,1,5,0,2,1,1,1,8,17,3,0.095296,0.158371,0.154134
233576,1006003,313342,0,4,17,2,1,0,5,0,0,1,0.313631,0.113122,0.125480
233577,1006010,223542,1,3,0,2,1,0,1,8,17,3,0.208685,0.174208,0.152035
233578,1006013,20342,0,2,20,2,3,0,1,2,0,2,0.186972,0.063348,0.126931
233579,1006016,14842,1,4,1,1,1,1,1,2,5,3,0.235223,0.513575,0.301982
233580,1006016,109542,1,4,1,1,1,1,8,14,17,3,0.243667,0.513575,0.301982
233581,1006018,71442,1,3,1,2,3,0,15,17,0,2,0.404101,0.101810,0.098269
233582,1006021,112542,1,2,12,1,2,1,1,11,15,3,0.595899,0.074661,0.215758
233583,1006021,3442,1,2,12,1,2,1,4,5,8,3,0.469240,0.074661,0.215758
233584,1006023,262242,1,2,0,2,2,1,1,11,16,3,0.211098,0.070136,0.141345
233585,1006025,161142,0,2,1,1,1,0,11,0,0,1,0.013269,0.176471,0.208915
233586,1006026,110742,1,3,6,2,1,1,1,2,8,3,0.820265,0.054299,0.095437
233587,1006028,162442,1,1,4,0,4,0,1,16,0,2,0.118215,0.020362,0.370449
233588,1006030,129842,1,2,17,2,1,1,6,8,15,3,0.287093,0.085973,0.095437
233589,1006030,241442,1,2,17,2,1,1,2,15,0,2,0.065139,0.085973,0.091219
233590,1006032,252442,1,4,7,0,3,0,8,0,0,1,0.107358,0.065611,0.370449
233591,1006033,127642,1,5,13,1,1,1,1,2,15,3,0.437877,0.036199,0.215758
233592,1006035,135742,0,2,1,2,3,0,6,8,0,2,0.184560,0.151584,0.132974
233593,1006036,255442,0,2,15,1,4,1,8,0,0,1,0.009650,0.463801,0.310118
233594,1006036,118942,0,2,15,1,4,1,8,0,0,1,0.090470,0.463801,0.310118
233595,1006036,254642,0,2,15,1,4,1,5,8,0,2,0.083233,0.463801,0.310118
233596,1006036,31842,0,2,15,1,4,1,1,5,12,3,0.094089,0.463801,0.310118
233597,1006037,124742,0,4,1,2,4,0,10,16,0,2,0.102533,0.092760,0.119494
233598,1006039,316642,0,4,0,1,4,1,4,5,0,2,0.200241,0.065611,0.072125

In [31]:
test_data = test_data.drop(['Purchase'], axis=1)

In [32]:
prediction = lm.predict(test_data)

In [33]:
prediction

array([0.27773905, 0.14971595, 0.2064054 , ..., 0.18488663, 0.09479551,
       0.21886811])

In [34]:
test_data.size

3270386

In [35]:
prediction.size

233599

In [36]:
linear_model_solution = test_data[['User_ID', 'Product_ID']]

In [37]:
linear_model_solution['Purchase'] = prediction

/Users/suhaniladani/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [38]:
linear_model_solution

        User_ID  Product_ID  Purchase
0       1000004      128942  0.277739
1       1000009      113442  0.149716
2       1000010      288442  0.206405
3       1000010      145342  0.215402
4       1000011       53842  0.115533
5       1000013      350442  0.145973
6       1000013      155442  0.154592
7       1000013       94542  0.158326
8       1000015      161842  0.356478
9       1000022       67942  0.362386
10      1000026       46742  0.253929
11      1000026       40042  0.250831
12      1000026      196542  0.240787
13      1000026        4542  0.250771
14      1000028      159542  0.113150
15      1000029      111542  0.145652
16      1000033      121042  0.346861
17      1000033      344442  0.343927
18      1000034      265242  0.333363
19      1000035       96642  0.154879
20      1000036      303042  0.232418
21      1000036       59642  0.247510
22      1000042       30842  0.151963
23      1000045      346442  0.329943
24      1000045      357242  0.326478
25      1000045      284742  0.327206
26      1000048      110842  0.234830
27      1000048      251642  0.227684
28      1000053      136742  0.214501
29      1000053       97342  0.216158
...         ...         ...       ...
233569  1005996      184242  0.182562
233570  1005996       45342  0.198828
233571  1006001      124642  0.317634
233572  1006002      121142  0.124973
233573  1006002      233542  0.123529
233574  1006002      226342  0.113456
233575  1006002      284842  0.121506
233576  1006003      313342  0.091913
233577  1006010      223542  0.115838
233578  1006013       20342  0.120567
233579  1006016       14842  0.202026
233580  1006016      109542  0.186739
233581  1006018       71442  0.119910
233582  1006021      112542  0.259563
233583  1006021        3442  0.263361
233584  1006023      262242  0.137285
233585  1006025      161142  0.195290
233586  1006026      110742  0.149114
233587  1006028      162442  0.370281
233588  1006030      129842  0.139304
233589  1006030      241442  0.137189
233590  1006032      252442  0.353528
233591  1006033      127642  0.262983
233592  1006035      135742  0.092623
233593  1006036      255442  0.168643
233594  1006036      118942  0.175262
233595  1006036      254642  0.170023
233596  1006036       31842  0.184887
233597  1006037      124742  0.094796
233598  1006039      316642  0.218868

[233599 rows x 3 columns]

In [39]:
linear_model_solution.to_csv('LinearRegressionResult.csv')

In [40]:
train_data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Category_Count,Product_Score,User_Score
0,1000001,69042,0,0,10,0,2,0,3,0,0,8370,1,0.120745,0.034113
1,1000001,248942,0,0,10,0,2,0,1,6,14,15200,3,0.309043,0.034113
2,1000001,87842,0,0,10,0,2,0,12,0,0,1422,1,0.054255,0.034113
3,1000001,85442,0,0,10,0,2,0,12,14,0,1057,2,0.181383,0.034113
4,1000002,285442,1,6,16,2,4,0,8,0,0,7969,1,0.107979,0.075049
5,1000003,193542,1,2,15,0,3,0,1,2,0,15227,2,0.327128,0.028265
6,1000004,184942,1,4,7,1,2,1,1,8,17,19215,3,0.765957,0.013645
7,1000004,346142,1,4,7,1,2,1,1,15,0,15854,2,0.315426,0.013645
8,1000004,97242,1,4,7,1,2,1,1,16,0,15686,2,0.485106,0.013645
9,1000005,274942,1,2,20,0,1,1,8,0,0,7871,1,0.421809,0.103314
10,1000005,251242,1,2,20,0,1,1,5,11,0,5254,2,0.631383,0.103314
11,1000005,14542,1,2,20,0,1,1,8,0,0,3957,1,0.357447,0.103314
12,1000005,31342,1,2,20,0,1,1,8,0,0,6073,1,0.019149,0.103314
13,1000005,145042,1,2,20,0,1,1,1,2,5,15665,3,0.747872,0.103314
14,1000006,231342,0,5,9,0,1,0,5,8,14,5378,3,0.044149,0.045809
15,1000006,190242,0,5,9,0,1,0,4,5,0,2079,2,0.101064,0.045809
16,1000006,96642,0,5,9,0,1,0,2,3,4,13055,3,0.092553,0.045809
17,1000006,58442,0,5,9,0,1,0,5,14,0,8851,2,0.293617,0.045809
18,1000007,36842,1,3,1,1,1,1,1,14,16,11788,3,0.470213,0.016569
19,1000008,249542,1,2,12,2,4,1,1,5,15,19614,3,0.417553,0.075049
20,1000008,220442,1,2,12,2,4,1,5,14,0,8584,2,0.681915,0.075049
21,1000008,156442,1,2,12,2,4,1,8,0,0,9872,1,0.444149,0.075049
22,1000008,213742,1,2,12,2,4,1,8,0,0,9743,1,0.186702,0.075049
23,1000008,214442,1,2,12,2,4,1,8,0,0,5982,1,0.267021,0.075049
24,1000008,303442,1,2,12,2,4,1,1,8,14,11927,3,0.189362,0.075049
25,1000009,135742,1,2,17,2,0,0,6,8,0,16662,2,0.218085,0.056530
26,1000009,39942,1,2,17,2,0,0,8,0,0,5887,1,0.088830,0.056530
27,1000009,161442,1,2,17,2,0,0,5,14,0,6973,2,0.267553,0.056530
28,1000009,78742,1,2,17,2,0,0,5,8,14,5391,3,0.150000,0.056530
29,1000010,85942,0,3,1,1,4,1,2,4,8,16352,3,0.512234,0.217349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,375436,0,3,1,2,2,1,20,0,0,596,1,0.432979,0.100390
550039,1005996,371644,0,2,0,1,1,1,20,0,0,595,1,0.478191,0.320663
550040,1005997,370853,0,2,7,0,3,0,19,0,0,26,1,0.435106,0.028265
550041,1006000,371644,1,4,17,1,2,1,20,0,0,488,1,0.478191,0.273879
550042,1006002,371644,1,5,0,2,1,1,20,0,0,243,1,0.478191,0.177388
550043,1006003,370293,0,4,17,2,1,0,19,0,0,48,1,0.417553,0.146199
550044,1006004,370853,0,2,15,2,2,0,19,0,0,62,1,0.435106,0.033138
550045,1006005,371644,0,2,5,2,2,1,20,0,0,252,1,0.478191,0.048733
550046,1006006,375436,0,0,0,2,1,0,20,0,0,236,1,0.432979,0.067251
550047,1006009,372445,0,2,12,2,3,0,20,0,0,244,1,0.445213,0.031189
550048,1006010,371644,1,3,0,2,1,0,20,0,0,591,1,0.478191,0.172515
550049,1006011,375436,1,3,15,2,3,0,20,0,0,473,1,0.432979,0.102339
550050,1006012,371644,1,3,15,2,4,1,20,0,0,368,1,0.478191,0.015595
550051,1006013,375436,0,2,20,2,3,0,20,0,0,489,1,0.432979,0.073099
550052,1006016,375436,1,4,1,1,1,1,20,0,0,239,1,0.432979,0.491228
550053,1006017,371644,0,3,7,1,1,0,20,0,0,371,1,0.478191,0.017544
550054,1006018,370293,1,3,1,2,3,0,19,0,0,60,1,0.417553,0.079922
550055,1006019,372445,1,2,0,0,4,0,20,0,0,238,1,0.445213,0.052632
550056,1006022,375436,1,2,17,2,4,0,20,0,0,254,1,0.432979,0.026316
550057,1006023,370853,1,2,0,2,2,1,19,0,0,61,1,0.435106,0.085770
550058,1006024,372445,1,2,12,0,0,1,20,0,0,121,1,0.445213,0.058480
550059,1006025,370853,0,2,1,1,1,0,19,0,0,48,1,0.435106,0.147173
550060,1006026,371644,1,3,6,2,1,1,20,0,0,494,1,0.478191,0.045809
550061,1006029,372445,0,2,1,2,1,1,20,0,0,599,1,0.445213,0.016569
550062,1006032,372445,1,4,7,0,3,0,20,0,0,473,1,0.445213,0.053606
550063,1006033,372445,1,5,13,1,1,1,20,0,0,368,1,0.445213,0.035088
550064,1006035,375436,0,2,1,2,3,0,20,0,0,371,1,0.432979,0.148148
550065,1006036,375436,0,2,15,1,4,1,20,0,0,137,1,0.432979,0.500975
550066,1006038,375436,0,6,1,2,2,0,20,0,0,365,1,0.432979,0.011696
550067,1006039,371644,0,4,0,1,4,1,20,0,0,490,1,0.478191,0.072125

In [41]:
train_data.corr()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Category_Count,Product_Score,User_Score
User_ID,1.000000,-0.017619,-0.033474,0.032698,-0.023971,0.022859,-0.030737,0.020443,0.003825,0.003896,0.003605,0.004716,0.004270,0.003688,-0.032458
Product_ID,-0.017619,1.000000,0.021084,0.028892,0.009344,0.010162,-0.003162,0.013194,0.090193,-0.090600,-0.144360,-0.103961,-0.183299,-0.150652,-0.007608
Gender,-0.033474,0.021084,1.000000,-0.004262,0.117291,-0.004515,0.014660,-0.011603,-0.045594,-0.000954,0.036146,0.060346,0.026808,0.020456,0.073517
Age,0.032698,0.028892,-0.004262,1.000000,0.091463,0.123079,-0.004712,0.311738,0.061197,0.018770,-0.007422,0.015839,-0.021246,-0.020741,-0.060446
Occupation,-0.023971,0.009344,0.117291,0.091463,1.000000,0.034479,0.030005,0.024280,-0.007618,0.006712,0.012269,0.020833,0.011600,0.011679,-0.002929
City_Category,0.022859,0.010162,-0.004515,0.123079,0.034479,1.000000,0.019946,0.039790,-0.014364,0.016003,0.035525,0.061914,0.040739,0.109546,-0.522198
Stay_In_Current_City_Years,-0.030737,-0.003162,0.014660,-0.004712,0.030005,0.019946,1.000000,-0.012819,-0.004213,0.001262,0.001977,0.005422,0.002735,0.001470,-0.000280
Marital_Status,0.020443,0.013194,-0.011603,0.311738,0.024280,0.039790,-0.012819,1.000000,0.019888,0.001099,-0.004629,-0.000463,-0.011257,-0.010415,0.000678
Product_Category_1,0.003825,0.090193,-0.045594,0.061197,-0.007618,-0.014364,-0.004213,0.019888,1.000000,-0.067877,-0.385534,-0.343703,-0.518270,-0.205178,0.017748
Product_Category_2,0.003896,-0.090600,-0.000954,0.018770,0.006712,0.016003,0.001262,0.001099,-0.067877,1.000000,0.094750,0.052288,0.444873,0.098062,-0.027482
Product_Category_3,0.003605,-0.144360,0.036146,-0.007422,0.012269,0.035525,0.001977,-0.004629,-0.385534,0.094750,1.000000,0.288501,0.791044,0.262332,-0.050203
Purchase,0.004716,-0.103961,0.060346,0.015839,0.020833,0.061914,0.005422,-0.000463,-0.343703,0.052288,0.288501,1.000000,0.323187,0.308641,-0.090356
Category_Count,0.004270,-0.183299,0.026808,-0.021246,0.011600,0.040739,0.002735,-0.011257,-0.518270,0.444873,0.791044,0.323187,1.000000,0.314808,-0.060064
Product_Score,0.003688,-0.150652,0.020456,-0.020741,0.011679,0.109546,0.001470,-0.010415,-0.205178,0.098062,0.262332,0.308641,0.314808,1.000000,-0.207742
User_Score,-0.032458,-0.007608,0.073517,-0.060446,-0.002929,-0.522198,-0.000280,0.000678,0.017748,-0.027482,-0.050203,-0.090356,-0.060064,-0.207742,1.000000

In [42]:
from sklearn.linear_model import Ridge

In [43]:
ridgeReg = Ridge(alpha=0.05, normalize=True)

In [44]:
ridgeReg.fit(x_train, y_train)

Ridge(alpha=0.05, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=True, random_state=None, solver='auto', tol=0.001)

In [45]:
ridgePrediction = ridgeReg.predict(test_data)

In [46]:
ridgePrediction

array([0.27574656, 0.15459212, 0.20809418, ..., 0.18711657, 0.10134825,
       0.21936484])

In [47]:
test_data['Purchase'] = ridgePrediction

In [48]:
test_data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,Product_Score,User_Score,Purchase
0,1000004,128942,1,4,7,1,2,1,1,11,0,2,0.478890,0.002262,0.275747
1,1000009,113442,1,2,17,2,0,0,3,5,0,2,0.141134,0.061086,0.154592
2,1000010,288442,0,3,1,1,4,1,5,14,0,2,0.090470,0.228507,0.208094
3,1000010,145342,0,3,1,1,4,1,4,9,0,2,0.009650,0.228507,0.216559
4,1000011,53842,0,2,1,2,1,0,4,5,12,3,0.258142,0.090498,0.122062
5,1000013,350442,1,4,1,2,3,1,2,3,15,3,0.142340,0.058824,0.150548
6,1000013,155442,1,4,1,2,3,1,1,11,15,3,0.214717,0.058824,0.158690
7,1000013,94542,1,4,1,2,3,1,2,4,9,3,0.082027,0.058824,0.162129
8,1000015,161842,1,2,7,0,1,0,10,13,16,3,0.050663,0.104072,0.352013
9,1000022,67942,1,1,15,0,4,0,5,14,0,2,0.183353,0.178733,0.357278
10,1000026,46742,1,2,7,1,2,1,1,2,15,3,0.779252,0.226244,0.253330
11,1000026,40042,1,2,7,1,2,1,5,0,0,1,0.059107,0.226244,0.250558
12,1000026,196542,1,2,7,1,2,1,5,8,14,3,0.212304,0.226244,0.241284
13,1000026,4542,1,2,7,1,2,1,5,8,0,2,0.155609,0.226244,0.250520
14,1000028,159542,0,2,1,2,2,1,10,15,16,3,0.242461,0.072398,0.119941
15,1000029,111542,1,3,7,2,1,0,2,17,0,2,0.255730,0.067873,0.150473
16,1000033,121042,1,4,3,0,1,1,15,0,0,1,0.121834,0.221719,0.341645
17,1000033,344442,1,4,3,0,1,1,5,8,14,3,0.162847,0.221719,0.339144
18,1000034,265242,0,1,0,0,0,0,5,8,0,2,1.000000,0.067873,0.329613
19,1000035,96642,1,4,1,2,4,1,2,3,4,3,0.094089,0.095023,0.158666
20,1000036,303042,1,2,3,1,0,0,5,0,0,1,0.334138,0.190045,0.233302
21,1000036,59642,1,2,3,1,0,0,1,2,3,3,0.184560,0.190045,0.247643
22,1000042,30842,1,2,8,2,0,1,1,2,15,3,0.322075,0.133484,0.156601
23,1000045,346442,0,4,16,0,1,1,1,2,14,3,0.124246,0.167421,0.325679
24,1000045,357242,0,4,16,0,1,1,5,0,0,1,0.055489,0.167421,0.322242
25,1000045,284742,0,4,16,0,1,1,5,12,0,2,0.069964,0.167421,0.323021
26,1000048,110842,1,2,4,1,3,1,1,2,5,3,0.667069,0.350679,0.234918
27,1000048,251642,1,2,4,1,3,1,1,2,4,3,0.120627,0.350679,0.228462
28,1000053,136742,1,2,0,1,1,0,1,14,16,3,0.155609,0.382353,0.216326
29,1000053,97342,1,2,0,1,1,0,1,15,16,3,0.149578,0.382353,0.217896
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,1005996,184242,0,2,0,1,1,1,9,15,0,2,0.234017,0.309955,0.185347
233570,1005996,45342,0,2,0,1,1,1,1,5,17,3,0.174910,0.309955,0.200840
233571,1006001,124642,0,2,7,0,0,1,16,0,0,1,0.173703,0.142534,0.314137
233572,1006002,121142,1,5,0,2,1,1,8,0,0,1,0.178528,0.158371,0.129581
233573,1006002,233542,1,5,0,2,1,1,1,15,0,2,0.323281,0.158371,0.128295
233574,1006002,226342,1,5,0,2,1,1,11,15,0,2,0.316043,0.158371,0.118797
233575,1006002,284842,1,5,0,2,1,1,1,8,17,3,0.095296,0.158371,0.126674
233576,1006003,313342,0,4,17,2,1,0,5,0,0,1,0.313631,0.113122,0.098425
233577,1006010,223542,1,3,0,2,1,0,1,8,17,3,0.208685,0.174208,0.121881
233578,1006013,20342,0,2,20,2,3,0,1,2,0,2,0.186972,0.063348,0.126142
233579,1006016,14842,1,4,1,1,1,1,1,2,5,3,0.235223,0.513575,0.202850
233580,1006016,109542,1,4,1,1,1,1,8,14,17,3,0.243667,0.513575,0.188707
233581,1006018,71442,1,3,1,2,3,0,15,17,0,2,0.404101,0.101810,0.125539
233582,1006021,112542,1,2,12,1,2,1,1,11,15,3,0.595899,0.074661,0.258742
233583,1006021,3442,1,2,12,1,2,1,4,5,8,3,0.469240,0.074661,0.262228
233584,1006023,262242,1,2,0,2,2,1,1,11,16,3,0.211098,0.070136,0.142603
233585,1006025,161142,0,2,1,1,1,0,11,0,0,1,0.013269,0.176471,0.197676
233586,1006026,110742,1,3,6,2,1,1,1,2,8,3,0.820265,0.054299,0.152989
233587,1006028,162442,1,1,4,0,4,0,1,16,0,2,0.118215,0.020362,0.364773
233588,1006030,129842,1,2,17,2,1,1,6,8,15,3,0.287093,0.085973,0.144357
233589,1006030,241442,1,2,17,2,1,1,2,15,0,2,0.065139,0.085973,0.142353
233590,1006032,252442,1,4,7,0,3,0,8,0,0,1,0.107358,0.065611,0.347838
233591,1006033,127642,1,5,13,1,1,1,1,2,15,3,0.437877,0.036199,0.261170
233592,1006035,135742,0,2,1,2,3,0,6,8,0,2,0.184560,0.151584,0.099708
233593,1006036,255442,0,2,15,1,4,1,8,0,0,1,0.009650,0.463801,0.171660
233594,1006036,118942,0,2,15,1,4,1,8,0,0,1,0.090470,0.463801,0.177845
233595,1006036,254642,0,2,15,1,4,1,5,8,0,2,0.083233,0.463801,0.172996
233596,1006036,31842,0,2,15,1,4,1,1,5,12,3,0.094089,0.463801,0.187117
233597,1006037,124742,0,4,1,2,4,0,10,16,0,2,0.102533,0.092760,0.101348
233598,1006039,316642,0,4,0,1,4,1,4,5,0,2,0.200241,0.065611,0.219365

In [49]:
test_data.to_csv('RidgeResult.csv')

In [50]:
result_data = test_data[['User_ID', 'Product_ID', 'Purchase']]

In [51]:
result_data

        User_ID  Product_ID  Purchase
0       1000004      128942  0.275747
1       1000009      113442  0.154592
2       1000010      288442  0.208094
3       1000010      145342  0.216559
4       1000011       53842  0.122062
5       1000013      350442  0.150548
6       1000013      155442  0.158690
7       1000013       94542  0.162129
8       1000015      161842  0.352013
9       1000022       67942  0.357278
10      1000026       46742  0.253330
11      1000026       40042  0.250558
12      1000026      196542  0.241284
13      1000026        4542  0.250520
14      1000028      159542  0.119941
15      1000029      111542  0.150473
16      1000033      121042  0.341645
17      1000033      344442  0.339144
18      1000034      265242  0.329613
19      1000035       96642  0.158666
20      1000036      303042  0.233302
21      1000036       59642  0.247643
22      1000042       30842  0.156601
23      1000045      346442  0.325679
24      1000045      357242  0.322242
25      1000045      284742  0.323021
26      1000048      110842  0.234918
27      1000048      251642  0.228462
28      1000053      136742  0.216326
29      1000053       97342  0.217896
...         ...         ...       ...
233569  1005996      184242  0.185347
233570  1005996       45342  0.200840
233571  1006001      124642  0.314137
233572  1006002      121142  0.129581
233573  1006002      233542  0.128295
233574  1006002      226342  0.118797
233575  1006002      284842  0.126674
233576  1006003      313342  0.098425
233577  1006010      223542  0.121881
233578  1006013       20342  0.126142
233579  1006016       14842  0.202850
233580  1006016      109542  0.188707
233581  1006018       71442  0.125539
233582  1006021      112542  0.258742
233583  1006021        3442  0.262228
233584  1006023      262242  0.142603
233585  1006025      161142  0.197676
233586  1006026      110742  0.152989
233587  1006028      162442  0.364773
233588  1006030      129842  0.144357
233589  1006030      241442  0.142353
233590  1006032      252442  0.347838
233591  1006033      127642  0.261170
233592  1006035      135742  0.099708
233593  1006036      255442  0.171660
233594  1006036      118942  0.177845
233595  1006036      254642  0.172996
233596  1006036       31842  0.187117
233597  1006037      124742  0.101348
233598  1006039      316642  0.219365

[233599 rows x 3 columns]

In [52]:
result_data.to_csv('RidgeResult.csv')

In [53]:
from sklearn.linear_model import ElasticNet

In [54]:
eReg = ElasticNet(alpha=1, l1_ratio=0.5, normalize=False)

In [55]:
eReg.fit(x_train, y_train)

ElasticNet(alpha=1, copy_X=True, fit_intercept=True, l1_ratio=0.5,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [56]:
test_data.drop(['Purchase'], axis=1)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,Product_Score,User_Score
0,1000004,128942,1,4,7,1,2,1,1,11,0,2,0.478890,0.002262
1,1000009,113442,1,2,17,2,0,0,3,5,0,2,0.141134,0.061086
2,1000010,288442,0,3,1,1,4,1,5,14,0,2,0.090470,0.228507
3,1000010,145342,0,3,1,1,4,1,4,9,0,2,0.009650,0.228507
4,1000011,53842,0,2,1,2,1,0,4,5,12,3,0.258142,0.090498
5,1000013,350442,1,4,1,2,3,1,2,3,15,3,0.142340,0.058824
6,1000013,155442,1,4,1,2,3,1,1,11,15,3,0.214717,0.058824
7,1000013,94542,1,4,1,2,3,1,2,4,9,3,0.082027,0.058824
8,1000015,161842,1,2,7,0,1,0,10,13,16,3,0.050663,0.104072
9,1000022,67942,1,1,15,0,4,0,5,14,0,2,0.183353,0.178733
10,1000026,46742,1,2,7,1,2,1,1,2,15,3,0.779252,0.226244
11,1000026,40042,1,2,7,1,2,1,5,0,0,1,0.059107,0.226244
12,1000026,196542,1,2,7,1,2,1,5,8,14,3,0.212304,0.226244
13,1000026,4542,1,2,7,1,2,1,5,8,0,2,0.155609,0.226244
14,1000028,159542,0,2,1,2,2,1,10,15,16,3,0.242461,0.072398
15,1000029,111542,1,3,7,2,1,0,2,17,0,2,0.255730,0.067873
16,1000033,121042,1,4,3,0,1,1,15,0,0,1,0.121834,0.221719
17,1000033,344442,1,4,3,0,1,1,5,8,14,3,0.162847,0.221719
18,1000034,265242,0,1,0,0,0,0,5,8,0,2,1.000000,0.067873
19,1000035,96642,1,4,1,2,4,1,2,3,4,3,0.094089,0.095023
20,1000036,303042,1,2,3,1,0,0,5,0,0,1,0.334138,0.190045
21,1000036,59642,1,2,3,1,0,0,1,2,3,3,0.184560,0.190045
22,1000042,30842,1,2,8,2,0,1,1,2,15,3,0.322075,0.133484
23,1000045,346442,0,4,16,0,1,1,1,2,14,3,0.124246,0.167421
24,1000045,357242,0,4,16,0,1,1,5,0,0,1,0.055489,0.167421
25,1000045,284742,0,4,16,0,1,1,5,12,0,2,0.069964,0.167421
26,1000048,110842,1,2,4,1,3,1,1,2,5,3,0.667069,0.350679
27,1000048,251642,1,2,4,1,3,1,1,2,4,3,0.120627,0.350679
28,1000053,136742,1,2,0,1,1,0,1,14,16,3,0.155609,0.382353
29,1000053,97342,1,2,0,1,1,0,1,15,16,3,0.149578,0.382353
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,1005996,184242,0,2,0,1,1,1,9,15,0,2,0.234017,0.309955
233570,1005996,45342,0,2,0,1,1,1,1,5,17,3,0.174910,0.309955
233571,1006001,124642,0,2,7,0,0,1,16,0,0,1,0.173703,0.142534
233572,1006002,121142,1,5,0,2,1,1,8,0,0,1,0.178528,0.158371
233573,1006002,233542,1,5,0,2,1,1,1,15,0,2,0.323281,0.158371
233574,1006002,226342,1,5,0,2,1,1,11,15,0,2,0.316043,0.158371
233575,1006002,284842,1,5,0,2,1,1,1,8,17,3,0.095296,0.158371
233576,1006003,313342,0,4,17,2,1,0,5,0,0,1,0.313631,0.113122
233577,1006010,223542,1,3,0,2,1,0,1,8,17,3,0.208685,0.174208
233578,1006013,20342,0,2,20,2,3,0,1,2,0,2,0.186972,0.063348
233579,1006016,14842,1,4,1,1,1,1,1,2,5,3,0.235223,0.513575
233580,1006016,109542,1,4,1,1,1,1,8,14,17,3,0.243667,0.513575
233581,1006018,71442,1,3,1,2,3,0,15,17,0,2,0.404101,0.101810
233582,1006021,112542,1,2,12,1,2,1,1,11,15,3,0.595899,0.074661
233583,1006021,3442,1,2,12,1,2,1,4,5,8,3,0.469240,0.074661
233584,1006023,262242,1,2,0,2,2,1,1,11,16,3,0.211098,0.070136
233585,1006025,161142,0,2,1,1,1,0,11,0,0,1,0.013269,0.176471
233586,1006026,110742,1,3,6,2,1,1,1,2,8,3,0.820265,0.054299
233587,1006028,162442,1,1,4,0,4,0,1,16,0,2,0.118215,0.020362
233588,1006030,129842,1,2,17,2,1,1,6,8,15,3,0.287093,0.085973
233589,1006030,241442,1,2,17,2,1,1,2,15,0,2,0.065139,0.085973
233590,1006032,252442,1,4,7,0,3,0,8,0,0,1,0.107358,0.065611
233591,1006033,127642,1,5,13,1,1,1,1,2,15,3,0.437877,0.036199
233592,1006035,135742,0,2,1,2,3,0,6,8,0,2,0.184560,0.151584
233593,1006036,255442,0,2,15,1,4,1,8,0,0,1,0.009650,0.463801
233594,1006036,118942,0,2,15,1,4,1,8,0,0,1,0.090470,0.463801
233595,1006036,254642,0,2,15,1,4,1,5,8,0,2,0.083233,0.463801
233596,1006036,31842,0,2,15,1,4,1,1,5,12,3,0.094089,0.463801
233597,1006037,124742,0,4,1,2,4,0,10,16,0,2,0.102533,0.092760
233598,1006039,316642,0,4,0,1,4,1,4,5,0,2,0.200241,0.065611

In [57]:
test_data = test_data.drop(['Purchase'], axis=1)

In [58]:
elastic_result = eReg.predict(test_data)

In [59]:
elastic_result

array([0.250182  , 0.25062054, 0.24549549, ..., 0.23477007, 0.23205109,
       0.22642837])

In [60]:
test_data['Purchase'] = elastic_result

In [61]:
test_data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,Product_Score,User_Score,Purchase
0,1000004,128942,1,4,7,1,2,1,1,11,0,2,0.478890,0.002262,0.250182
1,1000009,113442,1,2,17,2,0,0,3,5,0,2,0.141134,0.061086,0.250621
2,1000010,288442,0,3,1,1,4,1,5,14,0,2,0.090470,0.228507,0.245495
3,1000010,145342,0,3,1,1,4,1,4,9,0,2,0.009650,0.228507,0.249684
4,1000011,53842,0,2,1,2,1,0,4,5,12,3,0.258142,0.090498,0.252356
5,1000013,350442,1,4,1,2,3,1,2,3,15,3,0.142340,0.058824,0.243669
6,1000013,155442,1,4,1,2,3,1,1,11,15,3,0.214717,0.058824,0.249376
7,1000013,94542,1,4,1,2,3,1,2,4,9,3,0.082027,0.058824,0.251159
8,1000015,161842,1,2,7,0,1,0,10,13,16,3,0.050663,0.104072,0.249183
9,1000022,67942,1,1,15,0,4,0,5,14,0,2,0.183353,0.178733,0.251913
10,1000026,46742,1,2,7,1,2,1,1,2,15,3,0.779252,0.226244,0.252518
11,1000026,40042,1,2,7,1,2,1,5,0,0,1,0.059107,0.226244,0.252721
12,1000026,196542,1,2,7,1,2,1,5,8,14,3,0.212304,0.226244,0.248134
13,1000026,4542,1,2,7,1,2,1,5,8,0,2,0.155609,0.226244,0.253756
14,1000028,159542,0,2,1,2,2,1,10,15,16,3,0.242461,0.072398,0.249211
15,1000029,111542,1,3,7,2,1,0,2,17,0,2,0.255730,0.067873,0.250616
16,1000033,121042,1,4,3,0,1,1,15,0,0,1,0.121834,0.221719,0.250329
17,1000033,344442,1,4,3,0,1,1,5,8,14,3,0.162847,0.221719,0.243784
18,1000034,265242,0,1,0,0,0,0,5,8,0,2,1.000000,0.067873,0.246102
19,1000035,96642,1,4,1,2,4,1,2,3,4,3,0.094089,0.095023,0.251030
20,1000036,303042,1,2,3,1,0,0,5,0,0,1,0.334138,0.190045,0.244993
21,1000036,59642,1,2,3,1,0,0,1,2,3,3,0.184560,0.190045,0.252110
22,1000042,30842,1,2,8,2,0,1,1,2,15,3,0.322075,0.133484,0.252935
23,1000045,346442,0,4,16,0,1,1,1,2,14,3,0.124246,0.167421,0.243689
24,1000045,357242,0,4,16,0,1,1,5,0,0,1,0.055489,0.167421,0.243379
25,1000045,284742,0,4,16,0,1,1,5,12,0,2,0.069964,0.167421,0.245498
26,1000048,110842,1,2,4,1,3,1,1,2,5,3,0.667069,0.350679,0.250576
27,1000048,251642,1,2,4,1,3,1,1,2,4,3,0.120627,0.350679,0.246454
28,1000053,136742,1,2,0,1,1,0,1,14,16,3,0.155609,0.382353,0.249802
29,1000053,97342,1,2,0,1,1,0,1,15,16,3,0.149578,0.382353,0.250956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,1005996,184242,0,2,0,1,1,1,9,15,0,2,0.234017,0.309955,0.230434
233570,1005996,45342,0,2,0,1,1,1,1,5,17,3,0.174910,0.309955,0.234496
233571,1006001,124642,0,2,7,0,0,1,16,0,0,1,0.173703,0.142534,0.232166
233572,1006002,121142,1,5,0,2,1,1,8,0,0,1,0.178528,0.158371,0.232265
233573,1006002,233542,1,5,0,2,1,1,1,15,0,2,0.323281,0.158371,0.228973
233574,1006002,226342,1,5,0,2,1,1,11,15,0,2,0.316043,0.158371,0.229183
233575,1006002,284842,1,5,0,2,1,1,1,8,17,3,0.095296,0.158371,0.227468
233576,1006003,313342,0,4,17,2,1,0,5,0,0,1,0.313631,0.113122,0.226637
233577,1006010,223542,1,3,0,2,1,0,1,8,17,3,0.208685,0.174208,0.229238
233578,1006013,20342,0,2,20,2,3,0,1,2,0,2,0.186972,0.063348,0.235179
233579,1006016,14842,1,4,1,1,1,1,1,2,5,3,0.235223,0.513575,0.235328
233580,1006016,109542,1,4,1,1,1,1,8,14,17,3,0.243667,0.513575,0.232556
233581,1006018,71442,1,3,1,2,3,0,15,17,0,2,0.404101,0.101810,0.233669
233582,1006021,112542,1,2,12,1,2,1,1,11,15,3,0.595899,0.074661,0.232453
233583,1006021,3442,1,2,12,1,2,1,4,5,8,3,0.469240,0.074661,0.235647
233584,1006023,262242,1,2,0,2,2,1,1,11,16,3,0.211098,0.070136,0.228066
233585,1006025,161142,0,2,1,1,1,0,11,0,0,1,0.013269,0.176471,0.231025
233586,1006026,110742,1,3,6,2,1,1,1,2,8,3,0.820265,0.054299,0.232491
233587,1006028,162442,1,1,4,0,4,0,1,16,0,2,0.118215,0.020362,0.230975
233588,1006030,129842,1,2,17,2,1,1,6,8,15,3,0.287093,0.085973,0.231920
233589,1006030,241442,1,2,17,2,1,1,2,15,0,2,0.065139,0.085973,0.228657
233590,1006032,252442,1,4,7,0,3,0,8,0,0,1,0.107358,0.065611,0.228332
233591,1006033,127642,1,5,13,1,1,1,1,2,15,3,0.437877,0.036199,0.231975
233592,1006035,135742,0,2,1,2,3,0,6,8,0,2,0.184560,0.151584,0.231735
233593,1006036,255442,0,2,15,1,4,1,8,0,0,1,0.009650,0.463801,0.228232
233594,1006036,118942,0,2,15,1,4,1,8,0,0,1,0.090470,0.463801,0.232227
233595,1006036,254642,0,2,15,1,4,1,5,8,0,2,0.083233,0.463801,0.228252
233596,1006036,31842,0,2,15,1,4,1,1,5,12,3,0.094089,0.463801,0.234770
233597,1006037,124742,0,4,1,2,4,0,10,16,0,2,0.102533,0.092760,0.232051
233598,1006039,316642,0,4,0,1,4,1,4,5,0,2,0.200241,0.065611,0.226428

In [62]:
test_data.to_csv('ElasticNetResult.csv')

In [63]:
elastic_csv = test_data[['User_ID', 'Product_ID', 'Purchase']]

In [64]:
elastic_csv

        User_ID  Product_ID  Purchase
0       1000004      128942  0.250182
1       1000009      113442  0.250621
2       1000010      288442  0.245495
3       1000010      145342  0.249684
4       1000011       53842  0.252356
5       1000013      350442  0.243669
6       1000013      155442  0.249376
7       1000013       94542  0.251159
8       1000015      161842  0.249183
9       1000022       67942  0.251913
10      1000026       46742  0.252518
11      1000026       40042  0.252721
12      1000026      196542  0.248134
13      1000026        4542  0.253756
14      1000028      159542  0.249211
15      1000029      111542  0.250616
16      1000033      121042  0.250329
17      1000033      344442  0.243784
18      1000034      265242  0.246102
19      1000035       96642  0.251030
20      1000036      303042  0.244993
21      1000036       59642  0.252110
22      1000042       30842  0.252935
23      1000045      346442  0.243689
24      1000045      357242  0.243379
25      1000045      284742  0.245498
26      1000048      110842  0.250576
27      1000048      251642  0.246454
28      1000053      136742  0.249802
29      1000053       97342  0.250956
...         ...         ...       ...
233569  1005996      184242  0.230434
233570  1005996       45342  0.234496
233571  1006001      124642  0.232166
233572  1006002      121142  0.232265
233573  1006002      233542  0.228973
233574  1006002      226342  0.229183
233575  1006002      284842  0.227468
233576  1006003      313342  0.226637
233577  1006010      223542  0.229238
233578  1006013       20342  0.235179
233579  1006016       14842  0.235328
233580  1006016      109542  0.232556
233581  1006018       71442  0.233669
233582  1006021      112542  0.232453
233583  1006021        3442  0.235647
233584  1006023      262242  0.228066
233585  1006025      161142  0.231025
233586  1006026      110742  0.232491
233587  1006028      162442  0.230975
233588  1006030      129842  0.231920
233589  1006030      241442  0.228657
233590  1006032      252442  0.228332
233591  1006033      127642  0.231975
233592  1006035      135742  0.231735
233593  1006036      255442  0.228232
233594  1006036      118942  0.232227
233595  1006036      254642  0.228252
233596  1006036       31842  0.234770
233597  1006037      124742  0.232051
233598  1006039      316642  0.226428

[233599 rows x 3 columns]

In [65]:
elastic_csv.to_csv('ElasticNetResult.csv')

In [66]:
test_data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,Product_Score,User_Score,Purchase
0,1000004,128942,1,4,7,1,2,1,1,11,0,2,0.478890,0.002262,0.250182
1,1000009,113442,1,2,17,2,0,0,3,5,0,2,0.141134,0.061086,0.250621
2,1000010,288442,0,3,1,1,4,1,5,14,0,2,0.090470,0.228507,0.245495
3,1000010,145342,0,3,1,1,4,1,4,9,0,2,0.009650,0.228507,0.249684
4,1000011,53842,0,2,1,2,1,0,4,5,12,3,0.258142,0.090498,0.252356
5,1000013,350442,1,4,1,2,3,1,2,3,15,3,0.142340,0.058824,0.243669
6,1000013,155442,1,4,1,2,3,1,1,11,15,3,0.214717,0.058824,0.249376
7,1000013,94542,1,4,1,2,3,1,2,4,9,3,0.082027,0.058824,0.251159
8,1000015,161842,1,2,7,0,1,0,10,13,16,3,0.050663,0.104072,0.249183
9,1000022,67942,1,1,15,0,4,0,5,14,0,2,0.183353,0.178733,0.251913
10,1000026,46742,1,2,7,1,2,1,1,2,15,3,0.779252,0.226244,0.252518
11,1000026,40042,1,2,7,1,2,1,5,0,0,1,0.059107,0.226244,0.252721
12,1000026,196542,1,2,7,1,2,1,5,8,14,3,0.212304,0.226244,0.248134
13,1000026,4542,1,2,7,1,2,1,5,8,0,2,0.155609,0.226244,0.253756
14,1000028,159542,0,2,1,2,2,1,10,15,16,3,0.242461,0.072398,0.249211
15,1000029,111542,1,3,7,2,1,0,2,17,0,2,0.255730,0.067873,0.250616
16,1000033,121042,1,4,3,0,1,1,15,0,0,1,0.121834,0.221719,0.250329
17,1000033,344442,1,4,3,0,1,1,5,8,14,3,0.162847,0.221719,0.243784
18,1000034,265242,0,1,0,0,0,0,5,8,0,2,1.000000,0.067873,0.246102
19,1000035,96642,1,4,1,2,4,1,2,3,4,3,0.094089,0.095023,0.251030
20,1000036,303042,1,2,3,1,0,0,5,0,0,1,0.334138,0.190045,0.244993
21,1000036,59642,1,2,3,1,0,0,1,2,3,3,0.184560,0.190045,0.252110
22,1000042,30842,1,2,8,2,0,1,1,2,15,3,0.322075,0.133484,0.252935
23,1000045,346442,0,4,16,0,1,1,1,2,14,3,0.124246,0.167421,0.243689
24,1000045,357242,0,4,16,0,1,1,5,0,0,1,0.055489,0.167421,0.243379
25,1000045,284742,0,4,16,0,1,1,5,12,0,2,0.069964,0.167421,0.245498
26,1000048,110842,1,2,4,1,3,1,1,2,5,3,0.667069,0.350679,0.250576
27,1000048,251642,1,2,4,1,3,1,1,2,4,3,0.120627,0.350679,0.246454
28,1000053,136742,1,2,0,1,1,0,1,14,16,3,0.155609,0.382353,0.249802
29,1000053,97342,1,2,0,1,1,0,1,15,16,3,0.149578,0.382353,0.250956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,1005996,184242,0,2,0,1,1,1,9,15,0,2,0.234017,0.309955,0.230434
233570,1005996,45342,0,2,0,1,1,1,1,5,17,3,0.174910,0.309955,0.234496
233571,1006001,124642,0,2,7,0,0,1,16,0,0,1,0.173703,0.142534,0.232166
233572,1006002,121142,1,5,0,2,1,1,8,0,0,1,0.178528,0.158371,0.232265
233573,1006002,233542,1,5,0,2,1,1,1,15,0,2,0.323281,0.158371,0.228973
233574,1006002,226342,1,5,0,2,1,1,11,15,0,2,0.316043,0.158371,0.229183
233575,1006002,284842,1,5,0,2,1,1,1,8,17,3,0.095296,0.158371,0.227468
233576,1006003,313342,0,4,17,2,1,0,5,0,0,1,0.313631,0.113122,0.226637
233577,1006010,223542,1,3,0,2,1,0,1,8,17,3,0.208685,0.174208,0.229238
233578,1006013,20342,0,2,20,2,3,0,1,2,0,2,0.186972,0.063348,0.235179
233579,1006016,14842,1,4,1,1,1,1,1,2,5,3,0.235223,0.513575,0.235328
233580,1006016,109542,1,4,1,1,1,1,8,14,17,3,0.243667,0.513575,0.232556
233581,1006018,71442,1,3,1,2,3,0,15,17,0,2,0.404101,0.101810,0.233669
233582,1006021,112542,1,2,12,1,2,1,1,11,15,3,0.595899,0.074661,0.232453
233583,1006021,3442,1,2,12,1,2,1,4,5,8,3,0.469240,0.074661,0.235647
233584,1006023,262242,1,2,0,2,2,1,1,11,16,3,0.211098,0.070136,0.228066
233585,1006025,161142,0,2,1,1,1,0,11,0,0,1,0.013269,0.176471,0.231025
233586,1006026,110742,1,3,6,2,1,1,1,2,8,3,0.820265,0.054299,0.232491
233587,1006028,162442,1,1,4,0,4,0,1,16,0,2,0.118215,0.020362,0.230975
233588,1006030,129842,1,2,17,2,1,1,6,8,15,3,0.287093,0.085973,0.231920
233589,1006030,241442,1,2,17,2,1,1,2,15,0,2,0.065139,0.085973,0.228657
233590,1006032,252442,1,4,7,0,3,0,8,0,0,1,0.107358,0.065611,0.228332
233591,1006033,127642,1,5,13,1,1,1,1,2,15,3,0.437877,0.036199,0.231975
233592,1006035,135742,0,2,1,2,3,0,6,8,0,2,0.184560,0.151584,0.231735
233593,1006036,255442,0,2,15,1,4,1,8,0,0,1,0.009650,0.463801,0.228232
233594,1006036,118942,0,2,15,1,4,1,8,0,0,1,0.090470,0.463801,0.232227
233595,1006036,254642,0,2,15,1,4,1,5,8,0,2,0.083233,0.463801,0.228252
233596,1006036,31842,0,2,15,1,4,1,1,5,12,3,0.094089,0.463801,0.234770
233597,1006037,124742,0,4,1,2,4,0,10,16,0,2,0.102533,0.092760,0.232051
233598,1006039,316642,0,4,0,1,4,1,4,5,0,2,0.200241,0.065611,0.226428

In [67]:
test_data = test_data.drop(['Purchase'], axis=1)

In [68]:
from sklearn.ensemble import ExtraTreesRegressor

eTreeReg = ExtraTreesRegressor(n_estimators=6)

eTreeReg.fit(x_train, y_train)

eTreeResult = eTreeReg.predict(test_data)

eTreeResult

test_data['Purchase'] = eTreeResult

e_tree_data = test_data[['User_ID', 'Product_ID', 'Purchase']]

e_tree_data

e_tree_data.to_csv('ExtraTressRegressor.csv')